<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'country_code' => '93', 'iso_code' => 'AF / AFG', 'world_region' => 'AS'],
            ['name' => 'Albania', 'country_code' => '355', 'iso_code' => 'AL / ALB', 'world_region' => 'EU'],
            ['name' => 'Algeria', 'country_code' => '213', 'iso_code' => 'DZ / DZA', 'world_region' => 'AF'],
            ['name' => 'American Samoa', 'country_code' => '1684', 'iso_code' => 'AS / ASM', 'world_region' => 'OCE'],
            ['name' => 'Andorra', 'country_code' => '376', 'iso_code' => 'AD / AND', 'world_region' => 'EU'],
            ['name' => 'Angola', 'country_code' => '244', 'iso_code' => 'AO / AGO', 'world_region' => 'AF'],
            ['name' => 'Anguilla', 'country_code' => '1264', 'iso_code' => 'AI / AIA', 'world_region' => 'NA'],
            ['name' => 'Antarctica', 'country_code' => '672', 'iso_code' => 'AQ / ATA', 'world_region' => 'AN'],
            ['name' => 'Antigua and Barbuda', 'country_code' => '1268', 'iso_code' => 'AG / ATG', 'world_region' => 'NA'],
            ['name' => 'Argentina', 'country_code' => '54', 'iso_code' => 'AR / ARG', 'world_region' => 'SA'],
            ['name' => 'Armenia', 'country_code' => '374', 'iso_code' => 'AM / ARM', 'world_region' => 'AS'],
            ['name' => 'Aruba', 'country_code' => '297', 'iso_code' => 'AW / ABW', 'world_region' => 'NA'],
            ['name' => 'Australia', 'country_code' => '61', 'iso_code' => 'AU / AUS', 'world_region' => 'OCE'],
            ['name' => 'Austria', 'country_code' => '43', 'iso_code' => 'AT / AUT', 'world_region' => 'EU'],
            ['name' => 'Azerbaijan', 'country_code' => '994', 'iso_code' => 'AZ / AZE', 'world_region' => 'AS'],
            ['name' => 'Bahamas', 'country_code' => '1242', 'iso_code' => 'BS / BHS', 'world_region' => 'NA'],
            ['name' => 'Bahrain', 'country_code' => '973', 'iso_code' => 'BH / BHR', 'world_region' => 'AS'],
            ['name' => 'Bangladesh', 'country_code' => '880', 'iso_code' => 'BD / BGD', 'world_region' => 'AS'],
            ['name' => 'Barbados', 'country_code' => '1246', 'iso_code' => 'BB / BRB', 'world_region' => 'NA'],
            ['name' => 'Belarus', 'country_code' => '375', 'iso_code' => 'BY / BLR', 'world_region' => 'EU'],
            ['name' => 'Belgium', 'country_code' => '32', 'iso_code' => 'BE / BEL', 'world_region' => 'EU'],
            ['name' => 'Belize', 'country_code' => '501', 'iso_code' => 'BZ / BLZ', 'world_region' => 'NA'],
            ['name' => 'Benin', 'country_code' => '229', 'iso_code' => 'BJ / BEN', 'world_region' => 'AF'],
            ['name' => 'Bermuda', 'country_code' => '1441', 'iso_code' => 'BM / BMU', 'world_region' => 'NA'],
            ['name' => 'Bhutan', 'country_code' => '975', 'iso_code' => 'BT / BTN', 'world_region' => 'AS'],
            ['name' => 'Bolivia', 'country_code' => '591', 'iso_code' => 'BO / BOL', 'world_region' => 'SA'],
            ['name' => 'Bosnia and Herzegovina', 'country_code' => '387', 'iso_code' => 'BA / BIH', 'world_region' => 'EU'],
            ['name' => 'Botswana', 'country_code' => '267', 'iso_code' => 'BW / BWA', 'world_region' => 'AF'],
            ['name' => 'Brazil', 'country_code' => '55', 'iso_code' => 'BR / BRA', 'world_region' => 'SA'],
            ['name' => 'British Indian Ocean Territory', 'country_code' => '246', 'iso_code' => 'IO / IOT', 'world_region' => 'AS'],
            ['name' => 'British Virgin Islands', 'country_code' => '1284', 'iso_code' => 'VG / VGB', 'world_region' => 'NA'],
            ['name' => 'Brunei', 'country_code' => '673', 'iso_code' => 'BN / BRN', 'world_region' => 'AS'],
            ['name' => 'Bulgaria', 'country_code' => '359', 'iso_code' => 'BG / BGR', 'world_region' => 'EU'],
            ['name' => 'Burkina Faso', 'country_code' => '226', 'iso_code' => 'BF / BFA', 'world_region' => 'AF'],
            ['name' => 'Burundi', 'country_code' => '257', 'iso_code' => 'BI / BDI', 'world_region' => 'AF'],
            ['name' => 'Cambodia', 'country_code' => '855', 'iso_code' => 'KH / KHM', 'world_region' => 'AS'],
            ['name' => 'Cameroon', 'country_code' => '237', 'iso_code' => 'CM / CMR', 'world_region' => 'AF'],
            ['name' => 'Canada', 'country_code' => '1', 'iso_code' => 'CA / CAN', 'world_region' => 'NA'],
            ['name' => 'Cape Verde', 'country_code' => '238', 'iso_code' => 'CV / CPV', 'world_region' => 'AF'],
            ['name' => 'Cayman Islands', 'country_code' => '1345', 'iso_code' => 'KY / CYM', 'world_region' => 'NA'],
            ['name' => 'Central African Republic', 'country_code' => '236', 'iso_code' => 'CF / CAF', 'world_region' => 'AF'],
            ['name' => 'Chad', 'country_code' => '235', 'iso_code' => 'TD / TCD', 'world_region' => 'AF'],
            ['name' => 'Chile', 'country_code' => '56', 'iso_code' => 'CL / CHL', 'world_region' => 'SA'],
            ['name' => 'China', 'country_code' => '86', 'iso_code' => 'CN / CHN', 'world_region' => 'AS'],
            ['name' => 'Christmas Island', 'country_code' => '61', 'iso_code' => 'CX / CXR', 'world_region' => 'OCE'],
            ['name' => 'Cocos Islands', 'country_code' => '61', 'iso_code' => 'CC / CCK', 'world_region' => 'OCE'],
            ['name' => 'Colombia', 'country_code' => '57', 'iso_code' => 'CO / COL', 'world_region' => 'SA'],
            ['name' => 'Comoros', 'country_code' => '269', 'iso_code' => 'KM / COM', 'world_region' => 'AF'],
            ['name' => 'Cook Islands', 'country_code' => '682', 'iso_code' => 'CK / COK', 'world_region' => 'OCE'],
            ['name' => 'Costa Rica', 'country_code' => '506', 'iso_code' => 'CR / CRI', 'world_region' => 'NA'],
            ['name' => 'Croatia', 'country_code' => '385', 'iso_code' => 'HR / HRV', 'world_region' => 'EU'],
            ['name' => 'Cuba', 'country_code' => '53', 'iso_code' => 'CU / CUB', 'world_region' => 'NA'],
            ['name' => 'Curacao', 'country_code' => '599', 'iso_code' => 'CW / CUW', 'world_region' => 'NA'],
            ['name' => 'Cyprus', 'country_code' => '357', 'iso_code' => 'CY / CYP', 'world_region' => 'EU'],
            ['name' => 'Czech Republic', 'country_code' => '420', 'iso_code' => 'CZ / CZE', 'world_region' => 'EU'],
            ['name' => 'Denmark', 'country_code' => '45', 'iso_code' => 'DK / DNK', 'world_region' => 'EU'],
            ['name' => 'Djibouti', 'country_code' => '253', 'iso_code' => 'DJ / DJI', 'world_region' => 'AF'],
            ['name' => 'Dominica', 'country_code' => '1767', 'iso_code' => 'DM / DMA', 'world_region' => 'NA'],
            ['name' => 'Dominican Republic', 'country_code' => '1', 'iso_code' => 'DO / DOM', 'world_region' => 'NA'],
            ['name' => 'Ecuador', 'country_code' => '593', 'iso_code' => 'EC / ECU', 'world_region' => 'SA'],
            ['name' => 'Egypt', 'country_code' => '20', 'iso_code' => 'EG / EGY', 'world_region' => 'AF'],
            ['name' => 'El Salvador', 'country_code' => '503', 'iso_code' => 'SV / SLV', 'world_region' => 'NA'],
            ['name' => 'Equatorial Guinea', 'country_code' => '240', 'iso_code' => 'GQ / GNQ', 'world_region' => 'AF'],
            ['name' => 'Eritrea', 'country_code' => '291', 'iso_code' => 'ER / ERI', 'world_region' => 'AF'],
            ['name' => 'Estonia', 'country_code' => '372', 'iso_code' => 'EE / EST', 'world_region' => 'EU'],
            ['name' => 'Eswatini', 'country_code' => '268', 'iso_code' => 'SZ / SWZ', 'world_region' => 'AF'],
            ['name' => 'Ethiopia', 'country_code' => '251', 'iso_code' => 'ET / ETH', 'world_region' => 'AF'],
            ['name' => 'Fiji', 'country_code' => '679', 'iso_code' => 'FJ / FJI', 'world_region' => 'OCE'],
            ['name' => 'Finland', 'country_code' => '358', 'iso_code' => 'FI / FIN', 'world_region' => 'EU'],
            ['name' => 'France', 'country_code' => '33', 'iso_code' => 'FR / FRA', 'world_region' => 'EU'],
            ['name' => 'Gabon', 'country_code' => '241', 'iso_code' => 'GA / GAB', 'world_region' => 'AF'],
            ['name' => 'Gambia', 'country_code' => '220', 'iso_code' => 'GM / GMB', 'world_region' => 'AF'],
            ['name' => 'Georgia', 'country_code' => '995', 'iso_code' => 'GE / GEO', 'world_region' => 'AS'],
            ['name' => 'Germany', 'country_code' => '49', 'iso_code' => 'DE / DEU', 'world_region' => 'EU'],
            ['name' => 'Ghana', 'country_code' => '233', 'iso_code' => 'GH / GHA', 'world_region' => 'AF'],
            ['name' => 'Greece', 'country_code' => '30', 'iso_code' => 'GR / GRC', 'world_region' => 'EU'],
            ['name' => 'Grenada', 'country_code' => '1473', 'iso_code' => 'GD / GRD', 'world_region' => 'NA'],
            ['name' => 'Guadeloupe', 'country_code' => '590', 'iso_code' => 'GP / GUF', 'world_region' => 'NA'],
            ['name' => 'Guam', 'country_code' => '1671', 'iso_code' => 'GU / GUM', 'world_region' => 'OCE'],
            ['name' => 'Guatemala', 'country_code' => '502', 'iso_code' => 'GT / GTM', 'world_region' => 'NA'],
            ['name' => 'Guernsey', 'country_code' => '44', 'iso_code' => 'GG / GGY', 'world_region' => 'EU'],
            ['name' => 'Guinea', 'country_code' => '224', 'iso_code' => 'GN / GIN', 'world_region' => 'AF'],
            ['name' => 'Guinea-Bissau', 'country_code' => '245', 'iso_code' => 'GW / GNB', 'world_region' => 'AF'],
            ['name' => 'Guyana', 'country_code' => '592', 'iso_code' => 'GY / GUY', 'world_region' => 'SA'],
            ['name' => 'Haiti', 'country_code' => '509', 'iso_code' => 'HT / HTI', 'world_region' => 'NA'],
            ['name' => 'Honduras', 'country_code' => '504', 'iso_code' => 'HN / HND', 'world_region' => 'NA'],
            ['name' => 'Hong Kong', 'country_code' => '852', 'iso_code' => 'HK / HKG', 'world_region' => 'AS'],
            ['name' => 'Hungary', 'country_code' => '36', 'iso_code' => 'HU / HUN', 'world_region' => 'EU'],
            ['name' => 'Iceland', 'country_code' => '354', 'iso_code' => 'IS / ISL', 'world_region' => 'EU'],
            ['name' => 'India', 'country_code' => '91', 'iso_code' => 'IN / IND', 'world_region' => 'AS'],
            ['name' => 'Indonesia', 'country_code' => '62', 'iso_code' => 'ID / IDN', 'world_region' => 'AS'],
            ['name' => 'Iran', 'country_code' => '98', 'iso_code' => 'IR / IRN', 'world_region' => 'AS'],
            ['name' => 'Iraq', 'country_code' => '964', 'iso_code' => 'IQ / IRQ', 'world_region' => 'AS'],
            ['name' => 'Ireland', 'country_code' => '353', 'iso_code' => 'IE / IRL', 'world_region' => 'EU'],
            ['name' => 'Isle of Man', 'country_code' => '44', 'iso_code' => 'IM / IMN', 'world_region' => 'EU'],
            ['name' => 'Israel', 'country_code' => '972', 'iso_code' => 'IL / ISR', 'world_region' => 'AS'],
            ['name' => 'Italy', 'country_code' => '39', 'iso_code' => 'IT / ITA', 'world_region' => 'EU'],
            ['name' => 'Jamaica', 'country_code' => '1876', 'iso_code' => 'JM / JAM', 'world_region' => 'NA'],
            ['name' => 'Japan', 'country_code' => '81', 'iso_code' => 'JP / JPN', 'world_region' => 'AS'],
            ['name' => 'Jersey', 'country_code' => '44', 'iso_code' => 'JE / JEY', 'world_region' => 'EU'],
            ['name' => 'Jordan', 'country_code' => '962', 'iso_code' => 'JO / JOR', 'world_region' => 'AS'],
            ['name' => 'Kazakhstan', 'country_code' => '7', 'iso_code' => 'KZ / KAZ', 'world_region' => 'AS'],
            ['name' => 'Kenya', 'country_code' => '254', 'iso_code' => 'KE / KEN', 'world_region' => 'AF'],
            ['name' => 'Kiribati', 'country_code' => '686', 'iso_code' => 'KI / KIR', 'world_region' => 'OCE'],
            ['name' => 'Korea, North', 'country_code' => '850', 'iso_code' => 'KP / PRK', 'world_region' => 'AS'],
            ['name' => 'Korea, South', 'country_code' => '82', 'iso_code' => 'KR / KOR', 'world_region' => 'AS'],
            ['name' => 'Kuwait', 'country_code' => '965', 'iso_code' => 'KW / KWT', 'world_region' => 'AS'],
            ['name' => 'Kyrgyzstan', 'country_code' => '996', 'iso_code' => 'KG / KGZ', 'world_region' => 'AS'],
            ['name' => 'Laos', 'country_code' => '856', 'iso_code' => 'LA / LAO', 'world_region' => 'AS'],
            ['name' => 'Latvia', 'country_code' => '371', 'iso_code' => 'LV / LVA', 'world_region' => 'EU'],
            ['name' => 'Lebanon', 'country_code' => '961', 'iso_code' => 'LB / LBN', 'world_region' => 'AS'],
            ['name' => 'Lesotho', 'country_code' => '266', 'iso_code' => 'LS / LSO', 'world_region' => 'AF'],
            ['name' => 'Liberia', 'country_code' => '231', 'iso_code' => 'LR / LBR', 'world_region' => 'AF'],
            ['name' => 'Libya', 'country_code' => '218', 'iso_code' => 'LY / LBY', 'world_region' => 'AF'],
            ['name' => 'Liechtenstein', 'country_code' => '423', 'iso_code' => 'LI / LIE', 'world_region' => 'EU'],
            ['name' => 'Lithuania', 'country_code' => '370', 'iso_code' => 'LT / LTU', 'world_region' => 'EU'],
            ['name' => 'Luxembourg', 'country_code' => '352', 'iso_code' => 'LU / LUX', 'world_region' => 'EU'],
            ['name' => 'Macau', 'country_code' => '853', 'iso_code' => 'MO / MAC', 'world_region' => 'AS'],
            ['name' => 'Madagascar', 'country_code' => '261', 'iso_code' => 'MG / MDG', 'world_region' => 'AF'],
            ['name' => 'Malawi', 'country_code' => '265', 'iso_code' => 'MW / MWI', 'world_region' => 'AF'],
            ['name' => 'Malaysia', 'country_code' => '60', 'iso_code' => 'MY / MYS', 'world_region' => 'AS'],
            ['name' => 'Maldives', 'country_code' => '960', 'iso_code' => 'MV / MDV', 'world_region' => 'AS'],
            ['name' => 'Mali', 'country_code' => '223', 'iso_code' => 'ML / MLI', 'world_region' => 'AF'],
            ['name' => 'Malta', 'country_code' => '356', 'iso_code' => 'MT / MLT', 'world_region' => 'EU'],
            ['name' => 'Marshall Islands', 'country_code' => '692', 'iso_code' => 'MH / MHL', 'world_region' => 'OCE'],
            ['name' => 'Martinique', 'country_code' => '596', 'iso_code' => 'MQ / MTQ', 'world_region' => 'NA'],
            ['name' => 'Mauritania', 'country_code' => '222', 'iso_code' => 'MR / MRT', 'world_region' => 'AF'],
            ['name' => 'Mauritius', 'country_code' => '230', 'iso_code' => 'MU / MUS', 'world_region' => 'AF'],
            ['name' => 'Mayotte', 'country_code' => '262', 'iso_code' => 'YT / MYT', 'world_region' => 'AF'],
            ['name' => 'Mexico', 'country_code' => '52', 'iso_code' => 'MX / MEX', 'world_region' => 'NA'],
            ['name' => 'Micronesia', 'country_code' => '691', 'iso_code' => 'FM / FSM', 'world_region' => 'OCE'],
            ['name' => 'Moldova', 'country_code' => '373', 'iso_code' => 'MD / MDA', 'world_region' => 'EU'],
            ['name' => 'Monaco', 'country_code' => '377', 'iso_code' => 'MC / MCO', 'world_region' => 'EU'],
            ['name' => 'Mongolia', 'country_code' => '976', 'iso_code' => 'MN / MNG', 'world_region' => 'AS'],
            ['name' => 'Montenegro', 'country_code' => '382', 'iso_code' => 'ME / MNE', 'world_region' => 'EU'],
            ['name' => 'Montserrat', 'country_code' => '1664', 'iso_code' => 'MS / MSR', 'world_region' => 'NA'],
            ['name' => 'Morocco', 'country_code' => '212', 'iso_code' => 'MA / MAR', 'world_region' => 'AF'],
            ['name' => 'Mozambique', 'country_code' => '258', 'iso_code' => 'MZ / MOZ', 'world_region' => 'AF'],
            ['name' => 'Myanmar', 'country_code' => '95', 'iso_code' => 'MM / MMR', 'world_region' => 'AS'],
            ['name' => 'Namibia', 'country_code' => '264', 'iso_code' => 'NA / NAM', 'world_region' => 'AF'],
            ['name' => 'Nauru', 'country_code' => '674', 'iso_code' => 'NR / NRU', 'world_region' => 'OCE'],
            ['name' => 'Nepal', 'country_code' => '977', 'iso_code' => 'NP / NPL', 'world_region' => 'AS'],
            ['name' => 'Netherlands', 'country_code' => '31', 'iso_code' => 'NL / NLD', 'world_region' => 'EU'],
            ['name' => 'New Caledonia', 'country_code' => '687', 'iso_code' => 'NC / NCL', 'world_region' => 'OCE'],
            ['name' => 'New Zealand', 'country_code' => '64', 'iso_code' => 'NZ / NZL', 'world_region' => 'OCE'],
            ['name' => 'Nicaragua', 'country_code' => '505', 'iso_code' => 'NI / NIC', 'world_region' => 'NA'],
            ['name' => 'Niger', 'country_code' => '227', 'iso_code' => 'NE / NER', 'world_region' => 'AF'],
            ['name' => 'Nigeria', 'country_code' => '234', 'iso_code' => 'NG / NGA', 'world_region' => 'AF'],
            ['name' => 'Niue', 'country_code' => '683', 'iso_code' => 'NU / NIU', 'world_region' => 'OCE'],
            ['name' => 'Norfolk Island', 'country_code' => '672', 'iso_code' => 'NF / NFK', 'world_region' => 'OCE'],
            ['name' => 'Northern Mariana Islands', 'country_code' => '1670', 'iso_code' => 'MP / MNP', 'world_region' => 'OCE'],
            ['name' => 'Norway', 'country_code' => '47', 'iso_code' => 'NO / NOR', 'world_region' => 'EU'],
            ['name' => 'Oman', 'country_code' => '968', 'iso_code' => 'OM / OMN', 'world_region' => 'AS'],
            ['name' => 'Pakistan', 'country_code' => '92', 'iso_code' => 'PK / PAK', 'world_region' => 'AS'],
            ['name' => 'Palau', 'country_code' => '680', 'iso_code' => 'PW / PLW', 'world_region' => 'OCE'],
            ['name' => 'Panama', 'country_code' => '507', 'iso_code' => 'PA / PAN', 'world_region' => 'NA'],
            ['name' => 'Papua New Guinea', 'country_code' => '675', 'iso_code' => 'PG / PNG', 'world_region' => 'OCE'],
            ['name' => 'Paraguay', 'country_code' => '595', 'iso_code' => 'PY / PRY', 'world_region' => 'SA'],
            ['name' => 'Peru', 'country_code' => '51', 'iso_code' => 'PE / PER', 'world_region' => 'SA'],
            ['name' => 'Philippines', 'country_code' => '63', 'iso_code' => 'PH / PHL', 'world_region' => 'AS'],
            ['name' => 'Pitcairn Islands', 'country_code' => '64', 'iso_code' => 'PN / PCN', 'world_region' => 'OCE'],
            ['name' => 'Poland', 'country_code' => '48', 'iso_code' => 'PL / POL', 'world_region' => 'EU'],
            ['name' => 'Portugal', 'country_code' => '351', 'iso_code' => 'PT / PRT', 'world_region' => 'EU'],
            ['name' => 'Puerto Rico', 'country_code' => '1', 'iso_code' => 'PR / PRI', 'world_region' => 'NA'],
            ['name' => 'Qatar', 'country_code' => '974', 'iso_code' => 'QA / QAT', 'world_region' => 'AS'],
            ['name' => 'Romania', 'country_code' => '40', 'iso_code' => 'RO / ROU', 'world_region' => 'EU'],
            ['name' => 'Russia', 'country_code' => '7', 'iso_code' => 'RU / RUS', 'world_region' => 'EU'],
            ['name' => 'Rwanda', 'country_code' => '250', 'iso_code' => 'RW / RWA', 'world_region' => 'AF'],
            ['name' => 'Reunion', 'country_code' => '262', 'iso_code' => 'RE / REU', 'world_region' => 'AF'],
            ['name' => 'Saint Helena', 'country_code' => '290', 'iso_code' => 'SH / SHN', 'world_region' => 'AF'],
            ['name' => 'Saint Kitts and Nevis', 'country_code' => '1869', 'iso_code' => 'KN / KNA', 'world_region' => 'NA'],
            ['name' => 'Saint Lucia', 'country_code' => '1758', 'iso_code' => 'LC / LCA', 'world_region' => 'NA'],
            ['name' => 'Saint Pierre and Miquelon', 'country_code' => '508', 'iso_code' => 'PM / SPM', 'world_region' => 'NA'],
            ['name' => 'Saint Vincent and the Grenadines', 'country_code' => '1784', 'iso_code' => 'VC / VCT', 'world_region' => 'NA'],
            ['name' => 'Samoa', 'country_code' => '685', 'iso_code' => 'WS / WSM', 'world_region' => 'OCE'],
            ['name' => 'San Marino', 'country_code' => '378', 'iso_code' => 'SM / SMR', 'world_region' => 'EU'],
            ['name' => 'Sao Tome and Principe', 'country_code' => '239', 'iso_code' => 'ST / STP', 'world_region' => 'AF'],
            ['name' => 'Saudi Arabia', 'country_code' => '966', 'iso_code' => 'SA / SAU', 'world_region' => 'AS'],
            ['name' => 'Senegal', 'country_code' => '221', 'iso_code' => 'SN / SEN', 'world_region' => 'AF'],
            ['name' => 'Serbia', 'country_code' => '381', 'iso_code' => 'RS / SRB', 'world_region' => 'EU'],
            ['name' => 'Seychelles', 'country_code' => '248', 'iso_code' => 'SC / SYC', 'world_region' => 'AF'],
            ['name' => 'Sierra Leone', 'country_code' => '232', 'iso_code' => 'SL / SLE', 'world_region' => 'AF'],
            ['name' => 'Singapore', 'country_code' => '65', 'iso_code' => 'SG / SGP', 'world_region' => 'AS'],
            ['name' => 'Sint Maarten', 'country_code' => '1721', 'iso_code' => 'SX / SXM', 'world_region' => 'NA'],
            ['name' => 'Slovakia', 'country_code' => '421', 'iso_code' => 'SK / SVK', 'world_region' => 'EU'],
            ['name' => 'Slovenia', 'country_code' => '386', 'iso_code' => 'SI / SVN', 'world_region' => 'EU'],
            ['name' => 'Solomon Islands', 'country_code' => '677', 'iso_code' => 'SB / SLB', 'world_region' => 'OCE'],
            ['name' => 'Somalia', 'country_code' => '252', 'iso_code' => 'SO / SOM', 'world_region' => 'AF'],
            ['name' => 'South Africa', 'country_code' => '27', 'iso_code' => 'ZA / ZAF', 'world_region' => 'AF'],
            ['name' => 'South Sudan', 'country_code' => '211', 'iso_code' => 'SS / SSD', 'world_region' => 'AF'],
            ['name' => 'Spain', 'country_code' => '34', 'iso_code' => 'ES / ESP', 'world_region' => 'EU'],
            ['name' => 'Sri Lanka', 'country_code' => '94', 'iso_code' => 'LK / LKA', 'world_region' => 'AS'],
            ['name' => 'Sudan', 'country_code' => '249', 'iso_code' => 'SD / SDN', 'world_region' => 'AF'],
            ['name' => 'Suriname', 'country_code' => '597', 'iso_code' => 'SR / SUR', 'world_region' => 'SA'],
            ['name' => 'Svalbard', 'country_code' => '47', 'iso_code' => 'SJ / SJM', 'world_region' => 'EU'],
            ['name' => 'Sweden', 'country_code' => '46', 'iso_code' => 'SE / SWE', 'world_region' => 'EU'],
            ['name' => 'Switzerland', 'country_code' => '41', 'iso_code' => 'CH / CHE', 'world_region' => 'EU'],
            ['name' => 'Syria', 'country_code' => '963', 'iso_code' => 'SY / SYR', 'world_region' => 'AS'],
            ['name' => 'Taiwan', 'country_code' => '886', 'iso_code' => 'TW / TWN', 'world_region' => 'AS'],
            ['name' => 'Tajikistan', 'country_code' => '992', 'iso_code' => 'TJ / TJK', 'world_region' => 'AS'],
            ['name' => 'Tanzania', 'country_code' => '255', 'iso_code' => 'TZ / TZA', 'world_region' => 'AF'],
            ['name' => 'Thailand', 'country_code' => '66', 'iso_code' => 'TH / THA', 'world_region' => 'AS'],
            ['name' => 'Timor-Leste', 'country_code' => '670', 'iso_code' => 'TL / TLS', 'world_region' => 'AS'],
            ['name' => 'Togo', 'country_code' => '228', 'iso_code' => 'TG / TGO', 'world_region' => 'AF'],
            ['name' => 'Tokelau', 'country_code' => '690', 'iso_code' => 'TK / TKL', 'world_region' => 'OCE'],
            ['name' => 'Tonga', 'country_code' => '676', 'iso_code' => 'TO / TON', 'world_region' => 'OCE'],
            ['name' => 'Trinidad and Tobago', 'country_code' => '1868', 'iso_code' => 'TT / TTO', 'world_region' => 'NA'],
            ['name' => 'Tunisia', 'country_code' => '216', 'iso_code' => 'TN / TUN', 'world_region' => 'AF'],
            ['name' => 'Turkey', 'country_code' => '90', 'iso_code' => 'TR / TUR', 'world_region' => 'EU'],
            ['name' => 'Turkmenistan', 'country_code' => '993', 'iso_code' => 'TM / TUR', 'world_region' => 'AS'],
            ['name' => 'Tuvalu', 'country_code' => '688', 'iso_code' => 'TV / TUV', 'world_region' => 'OCE'],
            ['name' => 'Uganda', 'country_code' => '256', 'iso_code' => 'UG / UGA', 'world_region' => 'AF'],
            ['name' => 'Ukraine', 'country_code' => '380', 'iso_code' => 'UA / UKR', 'world_region' => 'EU'],
            ['name' => 'United Arab Emirates', 'country_code' => '971', 'iso_code' => 'AE / ARE', 'world_region' => 'AS'],
            ['name' => 'United Kingdom', 'country_code' => '44', 'iso_code' => 'GB / GBR', 'world_region' => 'EU'],
            ['name' => 'United States', 'country_code' => '1', 'iso_code' => 'US / USA', 'world_region' => 'NA'],
            ['name' => 'Uruguay', 'country_code' => '598', 'iso_code' => 'UY / URY', 'world_region' => 'SA'],
            ['name' => 'Uzbekistan', 'country_code' => '998', 'iso_code' => 'UZ / UZB', 'world_region' => 'AS'],
            ['name' => 'Vanuatu', 'country_code' => '678', 'iso_code' => 'VU / VUT', 'world_region' => 'OCE'],
            ['name' => 'Vatican City', 'country_code' => '39', 'iso_code' => 'VA / VAT', 'world_region' => 'EU'],
            ['name' => 'Venezuela', 'country_code' => '58', 'iso_code' => 'VE / VEN', 'world_region' => 'SA'],
            ['name' => 'Vietnam', 'country_code' => '84', 'iso_code' => 'VN / VNM', 'world_region' => 'AS'],
            ['name' => 'Wallis and Futuna', 'country_code' => '681', 'iso_code' => 'WF / WLF', 'world_region' => 'OCE'],
            ['name' => 'Western Sahara', 'country_code' => '212', 'iso_code' => 'EH / ESH', 'world_region' => 'AF'],
            ['name' => 'Yemen', 'country_code' => '967', 'iso_code' => 'YE / YEM', 'world_region' => 'AS'],
            ['name' => 'Zambia', 'country_code' => '260', 'iso_code' => 'ZM / ZMB', 'world_region' => 'AF'],
            ['name' => 'Zimbabwe', 'country_code' => '263', 'iso_code' => 'ZW / ZWE', 'world_region' => 'AF'],
        ];
        

        // Insert countries into the database
        DB::table('countries')->insert($countries);
    }
}
